nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-sources.cjs

npmScopes:
  mops-4.0:
    npmRegistryServer: "https://gp.mopssys.com/api/v4/packages/npm/"

npmRegistries:
  //gp.mopssys.com/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "glpat-41PeoBu1ZybQbGBUhzSV"
