export const START_GIST = 'START_GIST'
export const GET_GISTS_BY_USERNAME = 'GET_GISTS_BY_USERNAME'
export const GOTO_NEXT_PAGE = 'GOTO_NEXT_PAGE'
export const GOTO_PREV_PAGE = 'GOTO_PREV_PAGE'
export const BACK_TO_GRID = 'BACK_TO_GRID'

export const GOTO_GIST_DETAIL = 'GOTO_GIST_DETAIL'

export const RD_UPDATE_GISTS = 'RD_UPDATE_GISTS'
export const RD_LOADING_GISTS = 'RD_LOADING_GISTS'
export const RD_UPDATE_GIST_DETAIL = 'RD_UPDATE_GIST_DETAIL'
export const RD_LOADING_GIST_DETAIL = 'RD_LOADING_GIST_DETAIL'